name: Small size tests on OzStar supercomputer
run-name: Submitting workflow OzStar supercomputer using small sized data
on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types: [published]
jobs:
  run-small-tests-on-ozstar:
    runs-on: ubuntu-latest
    outputs:
      workflow_id: ${{ steps.run.outputs.workflowId }}
      workspace_id: ${{ steps.run.outputs.workspaceId }}
    steps:
      - uses: seqeralabs/action-tower-launch@v2
        id: run
        with:
          workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ secrets.TOWER_COMPUTE_ENV }}
          workdir: "/fred/oz005/users/nswainst/work"
          run_name: "Tower_test_small_${{ github.sha }}"
          revision: ${{ github.sha }}
          profiles: test
          pre_run_script: |
            module use /apps/users/pulsar/openstack/gcc-11.3.0/modulefiles
            module load java/11
            export PATH="$PATH:/home/nswainst"
          parameters: |
            {
                "upload": false
            }

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        if: github.event_name == 'pull_request'
        with:
          message: |
            Pipeline launched, monitor progress [here](${{ steps.run.outputs.workflowUrl }})
            Details:
              - Workflow ID: ${{ steps.run.outputs.workflowId }}
              - Workspace: ${{ steps.run.outputs.WorkspaceRef }}
              - Workspace ID: ${{ steps.run.outputs.workspaceId }}
              - Workflow URL: ${{ steps.run.outputs.workflowUrl }}
          comment_tag: towerrun

      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: Tower debug log file
          path: tower_action_*.log

  get_details:
    runs-on: ubuntu-latest
    needs: [run-small-tests-on-ozstar]
    steps:
      - name: Get run details
        run: |
          # Install TW CLI
          wget -L https://github.com/seqeralabs/tower-cli/releases/download/v0.7.3/tw-0.7.3-linux-x86_64
          sudo mv tw-* /usr/local/bin/tw
          chmod +x /usr/local/bin/tw

          # Use variables with ${{ needs.id.outputs.variable }} syntax
          tw -o json runs view \
              -w ${{ needs.run-small-tests-on-ozstar.outputs.workspace_id }} \
              -i ${{ needs.run-small-tests-on-ozstar.outputs.workflow_id }}
